name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  policy-test:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.16
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: install gotestsum
      run: go get -u gotest.tools/gotestsum

    - name: Download Dependencies
      run: |
        go mod tidy
        go mod download

    - name: Test
      run: gotestsum --format testname ./pkg/policies/opa/rego/...