on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://31c3-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: cf0ddcd3-c148-4bad-bd27-d417a65a1b36
          repo_url: https://github.com/patilpankaj212/terrascan-policies.git