on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://4aca-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: de35eacc-4bff-442e-9e35-ca7affb8001a
          repo_url: https://github.com/patilpankaj212/terrascan-policies.git