on:
  push:
  # TODO: only default branch
  workflow_dispatch:
    # Manual trigger

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: "terraform"
          iac_version: "v14"
          policy_type: "aws"
          only_warn: true
          verbose: false
          # config_path: .github/workflows/terrascan/config.yaml
